addons:
  postgresql: '9.3'

env:
  global:
  - AMAZON_S3_BUCKET=musicglue-bundle-cache
  - AMAZON_ACCESS_KEY_ID=AKIAITNVCO5SLJMTVVYQ
  - secure: SZBJ3ltbbVorx3XsvysFBFwINmljuLpIUWTuX3mBBgQBSuHwicncOg3wSlGIZ3ZUfBbGLFfqRQUVTzYx5hrdHJOOC6sIfXf/Or+OApsy8x/PB5Lep9MAD9MRixdudaxjbiQqpUYb3ROI40CwERfQjHYSug9mRmTnK+3ThH2a8mY=

rvm:
  - ruby-2.1.2

language: ruby

bundler_args: "--without development"

install:
  - "./script/cached-bundle install --deployment"

script:
  - bundle exec rake test:all

notifications:
  hipchat: 4c9312238a5ef355ef8e321fc2bab7@Music Glue
