env:
  global:
  - AMAZON_S3_BUCKET=musicglue-bundle-cache
  - AMAZON_ACCESS_KEY_ID=AKIAITNVCO5SLJMTVVYQ
  - secure: fewQhnxJOhA3u1EGnsbGu3GkfQiFJYt2PkR4gzmxl1iATlxjyMt7UHejInGjwkb9n6yb+uiKrE8iigWP6td+8330YtYnIyUhIvlIbxOpwgI3QhEFniHc7AsypJdcDP5zXPy8LyC1TNJ9Gnah7NcWi15SXr2VTfq4CUDcfVjPTGk=

rvm:
  - ruby-2.1.2

language: ruby

bundler_args: "--without development"

install:
  - "./script/cached-bundle install --deployment"

script:
  - bundle exec rake test:all

notifications:
  hipchat: 4c9312238a5ef355ef8e321fc2bab7@Music Glue
